default_language_version:
  python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        exclude: '\/fail_.*\.yaml'
    -   id: check-json
        exclude: '\/fail_.*\.json'
    -   id: check-ast
    -   id: check-toml
    -   id: check-xml
    -   id: forbid-new-submodules
    -   id: fix-byte-order-marker
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: [--maxkb=1000]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
    -   id: python-no-log-warn
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--config,config.ini]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--color, --settings-file,config.ini]
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args: [-vv, -i, -m, --fail-under=90, --exclude,build, --exclude,docs, --exclude,test, --exclude,sigma, --exclude,pySigma, --exclude,snowflake-connector-python]
