
name: Build WHLs

on:
  push:
    branches:
    - main

jobs:
    build_wheel:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10", "3.11", "3.12"]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python${{matrix.python-version}} -m pip install .

            - name: Build_WHL
              run: |
                python${{ matrix.python-version }} -m pip install --user --upgrade build
                mkdir -p /tmp/wheelhouse_${{ matrix.python-version }}
                python${{ matrix.python-version }} -m pip wheel --no-binary ":all:" --no-deps --wheel-dir=/tmp/wheelhouse_${{ matrix.python-version }} .

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                name: BuildArtifacts_python${{matrix.python-version}}
                path: /tmp/wheelhouse_${{ matrix.python-version }}/*.whl
                if-no-files-found: error
